### ISSUE TITLE
Face iteration is clunky

### ISSUE THREAD

**Issue by zthart** [zthart/wavedash#1]
Returning a 3-tuple out of the `object.faces()` iterator isn't ideal, and almost invalidates the purpose of having the `face` module - we can expose some functions in `face` that would make it simpler to iterate over them and get the data we care about.

**Comment by hearthsinger** [comment]
In #3, the `object.faces()` iterator was removed, and the member `faces` of an object will be a table containing all of the faces associated with the object. 

I'm keeping this open, because at the moment to really iterate through the faces you'd need something like the following:

```lua
-- Assuming we've created an object named teapot above, we want to get a table of 
-- vertex values that look like {v.x, v.y, v.z}, and every grouping of three vertices will be
-- created as a face on our canvas
--
-- As a note, this is how ss3d takes in model vertex data, so this is a legitimate usecase

local verts_in_order = {}
for _, face in ipairs(teapot.faces) do
    for _, vidx in ipairs(face.vindices) do
        local vert = teapot.vertices[vidx]
        verts_in_order[#verts_in_order+1] = {vert.x, vert.y, vert.z}
    end

    -- If we wanted to do something with texcoords or normals, we'd need to do another
    -- for ... in ipairs() for each of them
end
```
